version: "3.9"

services:
  duvua_main:
    restart: always
    container_name: duvua_main
    build:
      context: .
      dockerfile: ./main/Dockerfile
    env_file:
      - .env
    networks:
      - botjs
    depends_on:
      - postgresql
      - redisdb
    environment:
      NODE_ENV: "production"
      DEBUG_HIDE_DATE: 1
      NODE_NO_WARNINGS: 1

  duvua_music:
    restart: always
    container_name: duvua_music
    build:
      context: .
      dockerfile: ./music/Dockerfile
    env_file:
      - .env
    networks:
      - botjs
    depends_on:
      - postgresql

  postgresql:
    restart: always
    container_name: postgresql
    image: postgres:alpine
    volumes:
      - ./.docker_volumes/postgres_volume:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - botjs
    ports:
      - 25432:5432

  redisdb:
    restart: always
    container_name: redisdb
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning --requirepass "${REDIS_PASSWORD}"
    networks:
      - botjs
    env_file:
      - .env
    ports:
      - 26379:6379
    volumes:
      - ./.docker_volumes/redis_volume:/data

networks:
  botjs:
    driver: bridge
