version: '3.7'

services:
  # nodejs:
  #   container_name: nodejs
  #   build:
  #     context: ./docker/dev
  #     dockerfile: nodejs.dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./:/server
  #   networks:
  #     - botjs
  #   depends_on:
  #     - postgresql
  #     - redisdb
  #     - lavalink
  #   environment:
  #     DEBUG: "bot*"
  #     NODE_NO_WARNINGS: 1
  #   ports:
  #     - 5555:5555

  nodejs:
    container_name: nodejs
    build:
      context: .
      dockerfile: ./docker/duvuabot.dockerfile
    env_file:
      - .env
    networks:
      - botjs
    depends_on:
      - postgresql
      - redisdb
      - lavalink
    environment:
      DEBUG: "bot*"
      NODE_NO_WARNINGS: 1

  postgresql:
    container_name: postgresql
    image: postgres:alpine
    volumes:
      - ./.docker-volumes/postgres_volume:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - botjs
    ports:
      - 25432:5432

  redisdb:
    container_name: redisdb
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning --requirepass "${F_REDIS_PASSWORD}"
    networks:
      - botjs
    env_file:
      - .env
    ports:
      - 26379:6379
    volumes:
      - ./.docker-volumes/redis_volume:/data

  lavalink:
    container_name: lavalink
    build:
      context: ./docker/
      dockerfile: lavalink.dockerfile
    networks:
      - botjs
    env_file:
      - .env

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   networks:
  #     - botjs
  #   env_file:
  #     - .env
  #   environment:
  #     GUNICORN_ACCESS_LOGFILE: /dev/null
  #   ports:
  #     - 2280:80

networks:
  botjs:
    driver: bridge
